// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfspBEs6PwQDZzpEbB5KH_7XuRR35NgpQ',
    appId: '1:101156376612:web:ab8809fa9a060d5ee1c8b1',
    messagingSenderId: '101156376612',
    projectId: 'mobileappteam-586bc',
    authDomain: 'mobileappteam-586bc.firebaseapp.com',
    storageBucket: 'mobileappteam-586bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ldib3dYg4zamfizrzyLRTvr0Md4cvW8',
    appId: '1:101156376612:android:024c7a3dae7c9864e1c8b1',
    messagingSenderId: '101156376612',
    projectId: 'mobileappteam-586bc',
    storageBucket: 'mobileappteam-586bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZLXBXC5WsF_JnZ6NnEUEubCi90rRLlE8',
    appId: '1:101156376612:ios:84e825e2227bac73e1c8b1',
    messagingSenderId: '101156376612',
    projectId: 'mobileappteam-586bc',
    storageBucket: 'mobileappteam-586bc.firebasestorage.app',
    iosClientId: '101156376612-prp6gvuh85bb3teqfgi768qurgd4olg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moblieAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZLXBXC5WsF_JnZ6NnEUEubCi90rRLlE8',
    appId: '1:101156376612:ios:84e825e2227bac73e1c8b1',
    messagingSenderId: '101156376612',
    projectId: 'mobileappteam-586bc',
    storageBucket: 'mobileappteam-586bc.firebasestorage.app',
    iosClientId: '101156376612-prp6gvuh85bb3teqfgi768qurgd4olg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moblieAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfspBEs6PwQDZzpEbB5KH_7XuRR35NgpQ',
    appId: '1:101156376612:web:6faa753c5c12e665e1c8b1',
    messagingSenderId: '101156376612',
    projectId: 'mobileappteam-586bc',
    authDomain: 'mobileappteam-586bc.firebaseapp.com',
    storageBucket: 'mobileappteam-586bc.firebasestorage.app',
  );
}
