// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUI2cfmh0L8xLkA3DkzUMpNYbYvrmck4g',
    appId: '1:292172589182:web:11a1f5761cdeb917db102f',
    messagingSenderId: '292172589182',
    projectId: 'mad-project-eda74',
    authDomain: 'mad-project-eda74.firebaseapp.com',
    storageBucket: 'mad-project-eda74.firebasestorage.app',
    measurementId: 'G-4VKT6FWBEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5X3ZqJz9jKySNHvxs2uShvCl7pQfIsjM',
    appId: '1:292172589182:android:d91211eebbb84beedb102f',
    messagingSenderId: '292172589182',
    projectId: 'mad-project-eda74',
    storageBucket: 'mad-project-eda74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvh0bCYbg2MqTICi-KWUC3uR-VxBIvXXY',
    appId: '1:292172589182:ios:281cf4f2aee4a604db102f',
    messagingSenderId: '292172589182',
    projectId: 'mad-project-eda74',
    storageBucket: 'mad-project-eda74.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvh0bCYbg2MqTICi-KWUC3uR-VxBIvXXY',
    appId: '1:292172589182:ios:281cf4f2aee4a604db102f',
    messagingSenderId: '292172589182',
    projectId: 'mad-project-eda74',
    storageBucket: 'mad-project-eda74.firebasestorage.app',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUI2cfmh0L8xLkA3DkzUMpNYbYvrmck4g',
    appId: '1:292172589182:web:6413a58d51b1b1cddb102f',
    messagingSenderId: '292172589182',
    projectId: 'mad-project-eda74',
    authDomain: 'mad-project-eda74.firebaseapp.com',
    storageBucket: 'mad-project-eda74.firebasestorage.app',
    measurementId: 'G-TENSDFS9EX',
  );

}