// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK7FqdK9hBTx0mdfU3afQWCrZ9Gat7uP0',
    appId: '1:932808215673:web:35b6f3a6541b9cf5f8d8a8',
    messagingSenderId: '932808215673',
    projectId: 'finalterm-ae2a0',
    authDomain: 'finalterm-ae2a0.firebaseapp.com',
    storageBucket: 'finalterm-ae2a0.appspot.com',
    measurementId: 'G-KLLKGGRN38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkmwEJWSniPrF7Qen5WduMiaJaj9XE5U',
    appId: '1:932808215673:android:fd012a1b65cb529df8d8a8',
    messagingSenderId: '932808215673',
    projectId: 'finalterm-ae2a0',
    storageBucket: 'finalterm-ae2a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpC3ZAL7qiLsP0V0--M-5BXMmlWbCmvVw',
    appId: '1:932808215673:ios:79dee366118e8d9bf8d8a8',
    messagingSenderId: '932808215673',
    projectId: 'finalterm-ae2a0',
    storageBucket: 'finalterm-ae2a0.appspot.com',
    iosClientId: '932808215673-fkdc41d5ct7tg3l6brnitbtaojnf5li7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpC3ZAL7qiLsP0V0--M-5BXMmlWbCmvVw',
    appId: '1:932808215673:ios:79dee366118e8d9bf8d8a8',
    messagingSenderId: '932808215673',
    projectId: 'finalterm-ae2a0',
    storageBucket: 'finalterm-ae2a0.appspot.com',
    iosClientId: '932808215673-fkdc41d5ct7tg3l6brnitbtaojnf5li7.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );
}
